# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='slug',
            field=models.SlugField(default='default'),
        ),
    ]
