# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160601_2243'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='news',
            unique_together=set([('title', 'pub_time')]),
        ),
    ]
