# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160603_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='download_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 4, 21, 17, 45, 262000, tzinfo=utc)),
        ),
    ]
